configs = {
    'prep':{
        'max_workers': 0,
        'suffix': 'csv',
        'output_dir': '/path/to/output',
        'data_dir': '/path/to/dataset'
    },
    'sep2points':{
        'num_cached_parquet':10,
        'sequence_length' : int(1198),
        'batch_size': int(4096),
        # 'batch_size': int(128),
        'epochs':5,
        'lr':0.0001,
        'num_workers': 1,
        'parallel': False,
        'shuffle': True,
        'num_chached_parquet': 25,
        'device': 'cuda',
        'output_dir': '/path/to/output', 
        'data_dir': '/path/to/preprocessed/data',
        'stats_path': './utils/statistics_231214.csv',
        'ckp_path_root': '/aidata-nilm/seq2points/ckp',
        'output_dir': '/path/to/seq2points/evaluation/results/',
        'logger_name' : 'seq2point_1218',
        'logging': True,
        'wandb': False,
        'debug': True,
    },
    'unet':{
        'num_layers' : 7,
        'pooling_size': 16,
        'n_channels': 1,
        'num_classes': 1,
        'window_size' : (27000*3),
        'scheduler_kwargs' : {'factor': 0.1, 'patience': 5, 'mode': 'max'},
        'optim_kwargs': {'lr': 1e-3, 'betas': (0.9, 0.98)},
        'batch_size' : 12,
        'parallel': False, # True & batch size 128 이상 권장
        'epoch':5,
        'num_workers': 1,
        'taus': [0.025, 0.1, 0.5, 0.9, 0.975],
        'device': 'cuda',
        'stats_path': './utils/statistics_231214.csv',
        'ckp_path_root': '/aidata-nilm/unet/ckp',
        'output_dir': '/path/to/unet/evaluation/results',
        'data_dir': '/path/to/preprocessed/data',
        'labeling_dir': '/path/to/labels',
        'logger_name' : 'unet_1218',
        'parallel': False,
        'logging': True,
        'wandb': False,
        'debug': True,
    },
    'channel_device' : {
        # "01": "메인 분전반",
        "02": "TV",
        "03": "선풍기",
        "04": "전기포트",
        "05": "전기밥솥",
        "06": "세탁기",
        "07": "헤어드라이기",
        "08": "진공 청소기(유선)",
        "09": "전자레인지",
        "10": "에어프라이어",
        "11": "의류건조기",
        "12": "식기세척기",
        "13": "에어컨",
        "14": "전기장판, 담요",
        "15": "온수매트",
        "16": "인덕션(전기레인지)",
        "17": "컴퓨터",
        "18": "전기다리미",
        "19": "공기청정기",
        "20": "제습기",
        "21": "일반 냉장고",
        "22": "김치 냉장고",
        "23": "무선공유기/셋톱박스",
    }
}
